//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class band
    {
        public band()
        {
            this.albums = new HashSet<album>();
            this.members = new HashSet<member>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string country { get; set; }
        public System.DateTime formationDate { get; set; }
        public string genre { get; set; }
    
        public virtual ICollection<album> albums { get; set; }
        public virtual ICollection<member> members { get; set; }
    }
}
